### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by seleckis** [storyblok/nextjs-multilanguage-website#5]
Hi. I'm trying to run this project on localhost with my workspace. Once I change API token to mine than I get this error: 
```
Request failed with status code 404
Error: Request failed with status code 404
    at createError (/Users/seleckis/Sites/webskola/nextjs-multilanguage-website/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/seleckis/Sites/webskola/nextjs-multilanguage-website/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/seleckis/Sites/webskola/nextjs-multilanguage-website/node_modules/axios/lib/adapters/http.js:192:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
Could you please help me to figure out what is the problem with it?

**Comment by marckraw** [comment]
@seleckis Had the same problem, figure out that:

You have to create `en/settings` folder, and be sure, you have everything created, what was mentioned in this tutorial: https://www.storyblok.com/tp/next-js-react-guide 

It will not work out of the box, for completely new space, space need to be prepared as mentioned in tutorial.

**Comment by ademarCardoso** [comment]
Hello my friends, thanks for submitting this issue. And @marckraw , thank you very much for having answered this issue, really the problem mentioned above is the lack of exact space configuration.
